[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
# Environment variables will be set in Railway dashboard
# TELEGRAM_TOKEN
# ADMIN_USER_ID
# DEVELOPER_SECRET_KEY
# BASE_WEBHOOK_URL
# WEBHOOK_PORT=5000

