[build]
builder = "nixpacks"

[deploy]
startCommand = "python run_with_server.py"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
PORT = "5000"
PYTHONUNBUFFERED = "1"
TELEGRAM_TOKEN = ""
ADMIN_USER_ID = ""
BYBIT_API_KEY = ""
BYBIT_API_SECRET = ""