services:
  - type: web
    name: trading-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: ADMIN_USER_ID
        sync: false
      - key: BYBIT_API_KEY
        sync: false
      - key: BYBIT_API_SECRET
        sync: false
      - key: WEBHOOK_PORT
        value: 5000
      - key: PYTHON_VERSION
        value: 3.11.0
